import { useState } from 'react';
import type { SemanticMathObject } from '../../lib/math/types';

interface Props{operation:string;object:SemanticMathObject;running:boolean;onAction?:(operation:string,options?:Record<string,string|number|boolean>)=>void;}
const CONTROLLED=new Set(['lemma-rewrite','inequality-consequence','finite-quantifier-proof','induction-certificate','analysis-theorem-certificate','linear-algebra-theorem-certificate','finite-group-theorem-certificate']);
export function isE11ControlledOperation(operation:string):boolean{return CONTROLLED.has(operation);}

export function E11OperationControls({operation,object,running,onAction}:Props){
  const [target,setTarget]=useState('');const [lemma,setLemma]=useState('');const [direction,setDirection]=useState<'forward'|'reverse'>('forward');const [occurrence,setOccurrence]=useState<'first'|'all'>('first');
  const [variable,setVariable]=useState(object.kind==='function'?object.parameters[0]??'x':object.variables[0]??'x');const [predicate,setPredicate]=useState(`${variable} >= 0`);const [quantifier,setQuantifier]=useState<'forall'|'exists'>('forall');const [secondSet,setSecondSet]=useState('');const [secondVariable,setSecondVariable]=useState('y');const [secondQuantifier,setSecondQuantifier]=useState<'forall'|'exists'>('forall');
  const [baseFact,setBaseFact]=useState('S(1) = 1');const [recurrence,setRecurrence]=useState('S(k+1) = S(k) + (k+1)');const [index,setIndex]=useState(object.variables[0]??'n');const [stepVariable,setStepVariable]=useState('k');const [base,setBase]=useState('1');
  const [point,setPoint]=useState('0');const [linearTheorem,setLinearTheorem]=useState<'rank-nullity'|'invertible-matrix-equivalences'|'spectral-theorem-hermitian'>('rank-nullity');const [subset,setSubset]=useState('set(1)');
  if(operation==='lemma-rewrite')return <div className="operation-control"><label><span>Equality lemma</span><input value={lemma} onChange={e=>setLemma(e.target.value)} placeholder="a = b" /></label><label><span>Direction</span><select value={direction} onChange={e=>setDirection(e.target.value as typeof direction)}><option value="forward">Left → right</option><option value="reverse">Right → left</option></select></label><label><span>Occurrences</span><select value={occurrence} onChange={e=>setOccurrence(e.target.value as typeof occurrence)}><option value="first">First exact match</option><option value="all">All exact matches</option></select></label><label><span>Proposed target</span><input value={target} onChange={e=>setTarget(e.target.value)} /></label><button disabled={!lemma.trim()||!target.trim()||running} onClick={()=>onAction?.(operation,{lemma:lemma.trim(),target:target.trim(),direction,occurrence})}>Certify rewrite</button></div>;
  if(operation==='inequality-consequence')return <div className="operation-control"><label><span>Proposed consequence</span><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="x <= 3" /></label><button disabled={!target.trim()||running} onClick={()=>onAction?.(operation,{target:target.trim()})}>Prove consequence</button></div>;
  if(operation==='finite-quantifier-proof')return <div className="operation-control"><label><span>Outer quantifier</span><select value={quantifier} onChange={e=>setQuantifier(e.target.value as typeof quantifier)}><option value="forall">∀ universal</option><option value="exists">∃ existential</option></select></label><label><span>Bound variable</span><input value={variable} onChange={e=>setVariable(e.target.value)} /></label><label><span>Predicate</span><input value={predicate} onChange={e=>setPredicate(e.target.value)} placeholder="x^2 >= 0" /></label><label><span>Optional second finite set</span><input value={secondSet} onChange={e=>setSecondSet(e.target.value)} placeholder="set(1,2,3)" /></label>{secondSet.trim()&&<><label><span>Inner quantifier</span><select value={secondQuantifier} onChange={e=>setSecondQuantifier(e.target.value as typeof secondQuantifier)}><option value="forall">∀ universal</option><option value="exists">∃ existential</option></select></label><label><span>Inner variable</span><input value={secondVariable} onChange={e=>setSecondVariable(e.target.value)} /></label></>}<button disabled={!variable.trim()||!predicate.trim()||running} onClick={()=>onAction?.(operation,{variable:variable.trim(),predicate:predicate.trim(),quantifier,secondSet:secondSet.trim(),secondVariable:secondVariable.trim(),secondQuantifier})}>Discharge quantifier</button></div>;
  if(operation==='induction-certificate')return <div className="operation-control"><label><span>Claim index</span><input value={index} onChange={e=>setIndex(e.target.value)} /></label><label><span>Base integer</span><input value={base} inputMode="numeric" onChange={e=>setBase(e.target.value)} /></label><label><span>Verified base fact</span><input value={baseFact} onChange={e=>setBaseFact(e.target.value)} /></label><label><span>Step variable</span><input value={stepVariable} onChange={e=>setStepVariable(e.target.value)} /></label><label><span>Recurrence premise</span><input value={recurrence} onChange={e=>setRecurrence(e.target.value)} /></label><button disabled={!baseFact.trim()||!recurrence.trim()||!Number.isSafeInteger(Number(base))||running} onClick={()=>onAction?.(operation,{index:index.trim(),base:Number(base),baseFact:baseFact.trim(),stepVariable:stepVariable.trim(),recurrence:recurrence.trim()})}>Certify induction</button></div>;
  if(operation==='analysis-theorem-certificate')return <div className="operation-control"><label><span>Variable</span><input value={variable} onChange={e=>setVariable(e.target.value)} /></label><label><span>Point</span><input value={point} onChange={e=>setPoint(e.target.value)} /></label><button disabled={!variable.trim()||!point.trim()||running} onClick={()=>onAction?.(operation,{variable:variable.trim(),point:point.trim()})}>Apply theorem</button></div>;
  if(operation==='linear-algebra-theorem-certificate')return <div className="operation-control"><label><span>Theorem</span><select value={linearTheorem} onChange={e=>setLinearTheorem(e.target.value as typeof linearTheorem)}><option value="rank-nullity">Rank–nullity</option><option value="invertible-matrix-equivalences">Invertible matrix theorem</option><option value="spectral-theorem-hermitian">Hermitian spectral theorem</option></select></label><button disabled={running} onClick={()=>onAction?.(operation,{theorem:linearTheorem})}>Certify theorem</button></div>;
  if(operation==='finite-group-theorem-certificate')return <div className="operation-control"><label><span>Candidate subgroup</span><input value={subset} onChange={e=>setSubset(e.target.value)} /></label><button disabled={!subset.trim()||running} onClick={()=>onAction?.(operation,{subset:subset.trim()})}>Apply Lagrange theorem</button></div>;
  return null;
}
