import type { ToolCatalogItem } from './toolCatalog';

const ode='Numerical Math & ODEs' as const;
const algebra='Algebra' as const;
const analysis='Analysis' as const;
const vector='Vector Calculus' as const;
export const E10_TOOL_CATALOG:ToolCatalogItem[]=[
  {id:'pde-profile',operation:'pde-profile',label:'PDE classification & conditions',category:ode,phase:'E10',objectKinds:['pde'],description:'Classify a canonical heat, wave, or rectangular Laplace problem together with represented initial/boundary conditions.',example:'heatpde(1,1,[1,1/2])',aliases:['PDE','heat equation','wave equation','laplace equation','boundary conditions']},
  {id:'pde-separation-template',operation:'pde-separation-template',label:'Separation-of-variables template',category:ode,phase:'E10',objectKinds:['pde'],description:'Expose the exact separated eigenvalue/mode template for supported canonical PDE problems.',example:'wavepde(1,2,[1,0],[0,1])',aliases:['separation of variables','eigenfunctions','PDE modes']},
  {id:'pde-modal-solution',operation:'pde-modal-solution',label:'Canonical PDE modal solution',category:ode,phase:'E10',objectKinds:['pde'],description:'Build the exact finite sine-mode solution represented by the PDE constructor coefficients.',example:'laplacepde(1,1,[1,1/3])',aliases:['heat solution','wave solution','harmonic solution','Fourier modes']},
  {id:'finite-group-profile',operation:'finite-group-profile',label:'Finite group & Cayley-table profile',category:algebra,phase:'E10',objectKinds:['finite-group'],description:'Check associativity, identity, inverses, commutativity, cyclicity, and element orders exactly from a bounded Cayley table.',example:'group([[1,2,3],[2,3,1],[3,1,2]])',aliases:['group theory','cayley table','abelian','cyclic']},
  {id:'subgroup-check',operation:'subgroup-check',label:'Finite subgroup checker',category:algebra,phase:'E10',objectKinds:['finite-group'],description:'Certify whether a configured subset contains the identity and is closed under the group operation and inverses.',example:'group([[1,2,3],[2,3,1],[3,1,2]])',aliases:['subgroup','closure','inverse']},
  {id:'finite-ring-profile',operation:'finite-ring-profile',label:'Finite ring / field profile',category:algebra,phase:'E10',objectKinds:['finite-ring'],description:'Validate finite ring axioms from addition/multiplication tables and detect identity, units, zero divisors, commutativity, and field status.',example:'ring([[1,2,3],[2,3,1],[3,1,2]],[[1,1,1],[1,2,3],[1,3,2]])',aliases:['ring theory','field','finite field','zero divisor','unit']},
  {id:'group-homomorphism-profile',operation:'group-homomorphism-profile',label:'Group homomorphism, kernel & image',category:algebra,phase:'E10',objectKinds:['homomorphism'],description:'Check exact operation preservation between finite groups and derive kernel, image, injectivity, surjectivity, and isomorphism status.',example:'grouphom([[1,2,3],[2,3,1],[3,1,2]],[[1,2,3],[2,3,1],[3,1,2]],[1,3,2])',aliases:['homomorphism','kernel','image','isomorphism']},
  {id:'metric-space-profile',operation:'metric-space-profile',label:'Finite metric-space profile',category:analysis,phase:'E10',objectKinds:['metric-space'],description:'Validate metric axioms exactly and report diameter, separation, compactness, induced topology, and finite-space connectedness.',example:'metricspace([[0,1,2],[1,0,1],[2,1,0]])',aliases:['metric space','triangle inequality','compactness','distance']},
  {id:'metric-ball',operation:'metric-ball',label:'Metric ball',category:analysis,phase:'E10',objectKinds:['metric-space'],description:'Compute an exact open or closed ball around a configured point in a finite metric space.',example:'metricspace([[0,1,2],[1,0,1],[2,1,0]])',aliases:['open ball','closed ball','neighborhood']},
  {id:'finite-topology-profile',operation:'finite-topology-profile',label:'Finite topology profile',category:analysis,phase:'E10',objectKinds:['topology'],description:'Validate finite topology axioms from 0/1 incidence rows and certify discrete/indiscrete, T0/T1, connected, clopen, and compact properties.',example:'topology([[0,0],[1,0],[0,1],[1,1]])',aliases:['topology','open set','closed set','connected','compact']},
  {id:'topology-subset-profile',operation:'topology-subset-profile',label:'Open / closed / closure / interior',category:analysis,phase:'E10',objectKinds:['topology'],description:'Analyze a configured subset in a finite topology, including open/closed/clopen status, interior, closure, and boundary.',example:'topology([[0,0],[1,0],[0,1],[1,1]])',aliases:['interior','closure','boundary','clopen']},
  {id:'point-set-profile',operation:'point-set-profile',label:'Exact point-set geometry',category:vector,phase:'E10',objectKinds:['point-set'],description:'Compute exact centroid, coordinate bounds, affine dimension, collinearity, and coplanarity for finite 2D/3D point sets.',example:'pointset([[0,0],[1,1],[2,2]])',aliases:['analytic geometry','points','collinear','coplanar','affine dimension']},
  {id:'point-distance-matrix',operation:'point-distance-matrix',label:'Exact Euclidean distance matrix',category:vector,phase:'E10',objectKinds:['point-set'],description:'Build the exact symbolic Euclidean distance matrix for a finite point set, preserving irrational square roots.',example:'pointset([[0,0],[1,0],[0,1]])',aliases:['distance matrix','euclidean distance','point geometry']},
  {id:'affine-hull-profile',operation:'affine-hull-profile',label:'Affine hull',category:vector,phase:'E10',objectKinds:['point-set'],description:'Recover an exact affine point, line, plane, or full ambient hull from a finite 2D/3D point set.',example:'pointset([[0,0,0],[1,0,0],[0,1,0]])',aliases:['affine hull','line equation','plane equation','span']},
  {id:'geometry-profile',operation:'geometry-profile',label:'Owned curve / region / surface profile',category:vector,phase:'E10',objectKinds:['geometry'],description:'Inspect semantic rectangle, parameterized-curve, and graph-surface objects that own their geometry and bounds for later E2/E3 reuse.',example:'paramcurve([cos(t),sin(t)],0,2*pi)',aliases:['region','curve','surface','parameterization','geometry object']},
];
