import type { ToolCatalogItem } from './toolCatalog';

const proof='Proof & Verification' as const;
export const E11_TOOL_CATALOG:ToolCatalogItem[]=[
  {id:'theorem-registry',operation:'theorem-registry',label:'Deterministic theorem registry',category:proof,phase:'E11',objectKinds:[],description:'Browse the E11 theorem rules that have deterministic prerequisite and application checkers.',example:'x^2 = x^2',aliases:['theorems','lemma registry','proof rules'],specialRoute:'proof'},
  {id:'lemma-rewrite',operation:'lemma-rewrite',label:'Apply equality lemma',category:proof,phase:'E11',objectKinds:['expression','equation','inequality','function'],description:'Certify an exact AST-subtree substitution using a supplied equality lemma, in either direction.',example:'x*(y+z)',aliases:['substitution of equals','rewrite theorem','lemma application']},
  {id:'inequality-consequence',operation:'inequality-consequence',label:'Prove inequality consequence',category:proof,phase:'E11',objectKinds:['inequality'],description:'Certify a bounded one-way inequality implication by exact positive rational scaling and strict-to-nonstrict weakening.',example:'2*x < 6',aliases:['order theorem','inequality proof','positive scaling']},
  {id:'finite-quantifier-proof',operation:'finite-quantifier-proof',label:'Finite quantified proof',category:proof,phase:'E11',objectKinds:['finite-set'],description:'Discharge one or two nested finite-domain ∀/∃ obligations by exhaustive exact evaluation, with witnesses or counterexamples.',example:'set(1,2,3)',aliases:['forall','exists','quantifier proof','finite predicate']},
  {id:'induction-certificate',operation:'induction-certificate',label:'Recurrence-backed induction certificate',category:proof,phase:'E11',objectKinds:['equation'],description:'Certify an ordinary induction proof for a recursively defined sequence from a verified base fact, recurrence premise, and exact successor obligation.',example:'S(n) = n*(n+1)/2',aliases:['mathematical induction','induction hypothesis','base case','successor case']},
  {id:'analysis-theorem-certificate',operation:'analysis-theorem-certificate',label:'Analysis theorem certificate',category:proof,phase:'E11',objectKinds:['expression','function'],description:'Apply a supported real-analysis theorem only after its deterministic prerequisite is discharged; E11 starts with differentiability ⇒ continuity at a point.',example:'x^2',aliases:['differentiability implies continuity','analysis proof','theorem application']},
  {id:'linear-algebra-theorem-certificate',operation:'linear-algebra-theorem-certificate',label:'Linear-algebra theorem certificate',category:proof,phase:'E11',objectKinds:['matrix'],description:'Certify rank–nullity, bounded invertible-matrix equivalences, or the Hermitian spectral-theorem prerequisite and conclusion.',example:'[[1,0],[0,2]]',aliases:['rank nullity','invertible matrix theorem','spectral theorem','Hermitian']},
  {id:'finite-group-theorem-certificate',operation:'finite-group-theorem-certificate',label:'Finite-group theorem certificate',category:proof,phase:'E11',objectKinds:['finite-group'],description:"Apply Lagrange's theorem after exact finite-group and subgroup prerequisites are discharged.",example:'group([[1,2,3],[2,3,1],[3,1,2]])',aliases:['Lagrange theorem','subgroup order','group proof']},
];
