import type { ToolCatalogItem } from './toolCatalog';

export const E4_TOOL_CATALOG: ToolCatalogItem[] = [
  {
    id: 'ode-profile',
    operation: 'ode-profile',
    label: 'ODE / system profile',
    category: 'Numerical Math & ODEs',
    phase: 'E4',
    objectKinds: ['ode'],
    description: 'Inspect ODE order, state dimension, initial-data status, autonomous structure, and the represented vector field.',
    example: 'odesys([x,y], [y,-x], 0, [1,0])',
    aliases: ['ODE system', 'dynamical system', 'autonomous system'],
  },
  {
    id: 'ode-symbolic-solve',
    operation: 'ode-symbolic-solve',
    label: 'Symbolic ODE solve',
    category: 'Numerical Math & ODEs',
    phase: 'E4',
    objectKinds: ['ode'],
    description: 'Solve verified separable, first-order linear, exact differential, and bounded constant-coefficient second-order classes without inventing unsupported closed forms.',
    example: 'separable(1, y)',
    aliases: ['separable ODE', 'linear ODE', 'exact ODE', 'characteristic equation'],
  },
  {
    id: 'ode-to-system',
    operation: 'ode-to-system',
    label: 'Convert ODE to first-order system',
    category: 'Numerical Math & ODEs',
    phase: 'E4',
    objectKinds: ['ode'],
    description: 'Convert supported second- or higher-order constant-coefficient equations into equivalent first-order state systems.',
    example: 'oden([1,0,0,0], 0, 0, [1,0,0])',
    aliases: ['state space', 'higher order ODE', 'system conversion'],
  },
  {
    id: 'ode-equilibria',
    operation: 'ode-equilibria',
    label: 'Equilibrium points',
    category: 'Numerical Math & ODEs',
    phase: 'E4',
    objectKinds: ['ode'],
    description: 'Find equilibria of supported autonomous systems using exact linear or bounded decoupled solving.',
    example: 'odesys([x,y], [-x,-2*y])',
    aliases: ['fixed points', 'critical points', 'steady states'],
  },
  {
    id: 'ode-linearize',
    operation: 'ode-linearize',
    label: 'Jacobian linearization',
    category: 'Numerical Math & ODEs',
    phase: 'E4',
    objectKinds: ['ode'],
    description: 'Build the exact Jacobian and first-order local linear system at a certified autonomous-system equilibrium.',
    example: 'odesys([x,y], [x-x^3,-2*y])',
    aliases: ['Jacobian', 'local linearization', 'linearized system'],
  },
  {
    id: 'ode-stability',
    operation: 'ode-stability',
    label: 'Local stability classification',
    category: 'Numerical Math & ODEs',
    phase: 'E4',
    objectKinds: ['ode'],
    description: 'Classify planar equilibria from the exact rational Jacobian trace, determinant, discriminant, and eigenvalue real-part pattern, leaving nonhyperbolic cases explicitly inconclusive.',
    example: 'odesys([x,y], [-x,-2*y])',
    aliases: ['stability', 'phase plane', 'node', 'saddle', 'spiral', 'focus', 'center'],
  },
  {
    id: 'ode-adaptive-solve',
    operation: 'ode-adaptive-solve',
    label: 'Adaptive RK45 trajectory',
    category: 'Numerical Math & ODEs',
    phase: 'E4',
    objectKinds: ['ode'],
    description: 'Integrate scalar IVPs or first-order systems with adaptive Dormand–Prince RK45, event stopping, step diagnostics, and an explicit stiffness heuristic.',
    example: 'odesys([x,y], [y,-x], 0, [1,0])',
    aliases: ['RK45', 'Dormand Prince', 'adaptive Runge Kutta', 'event detection', 'stiffness'],
  },
];
