import type { ToolCatalogItem } from './toolCatalog';

export const E5_TOOL_CATALOG: ToolCatalogItem[] = [
  { id:'numerical-lu', operation:'numerical-lu', label:'Pivoted numerical LU', category:'Linear Algebra', phase:'E5', objectKinds:['matrix'], description:'Factor a resolved real square matrix numerically as PA≈LU with partial pivoting and residual diagnostics.', example:'[[4,2],[1,3]]', aliases:['LU decomposition','pivoted LU','Gaussian factorization'] },
  { id:'numerical-cholesky', operation:'numerical-cholesky', label:'Numerical Cholesky', category:'Linear Algebra', phase:'E5', objectKinds:['matrix'], description:'Compute A≈LLᵀ for a numerically symmetric positive-definite real matrix and expose the reconstruction residual.', example:'[[4,2],[2,3]]', aliases:['Cholesky','positive definite','LLT'] },
  { id:'numerical-qr', operation:'numerical-qr', label:'Householder numerical QR', category:'Linear Algebra', phase:'E5', objectKinds:['matrix'], description:'Compute a floating Householder QR factorization with reconstruction and orthogonality diagnostics.', example:'[[1,1],[1,-1],[1,2]]', aliases:['QR','Householder','orthogonal factorization'] },
  { id:'numerical-eigen', operation:'numerical-eigen', label:'Symmetric numerical eigenanalysis', category:'Linear Algebra', phase:'E5', objectKinds:['matrix'], description:'Compute eigenvalues and an orthonormal eigenvector basis for a real symmetric matrix using a bounded Jacobi iteration.', example:'[[2,1],[1,2]]', aliases:['eigenvalues','eigenvectors','Jacobi eigenvalue'] },
  { id:'numerical-svd', operation:'numerical-svd', label:'Singular value decomposition', category:'Linear Algebra', phase:'E5', objectKinds:['matrix'], description:'Compute a bounded floating SVD baseline through the symmetric eigendecomposition of AᵀA, with explicit conditioning limitations.', example:'[[1,2],[2,4],[0,1]]', aliases:['SVD','singular values','singular vectors'] },
  { id:'pseudoinverse', operation:'pseudoinverse', label:'Moore–Penrose pseudoinverse', category:'Linear Algebra', phase:'E5', objectKinds:['matrix'], description:'Construct a tolerance-dependent Moore–Penrose pseudoinverse from the E5 singular-value decomposition.', example:'[[1,2],[2,4],[0,1]]', aliases:['pseudoinverse','pinv','Moore Penrose'] },
  { id:'numerical-rank', operation:'numerical-rank', label:'Tolerance-aware numerical rank', category:'Linear Algebra', phase:'E5', objectKinds:['matrix'], description:'Classify effective floating rank from singular values and an explicit numerical threshold.', example:'[[1,2],[2,4]]', aliases:['rank','effective rank','numerical rank'] },
  { id:'spectral-condition', operation:'spectral-condition', label:'Spectral condition number', category:'Linear Algebra', phase:'E5', objectKinds:['matrix'], description:'Estimate κ₂ from the largest and smallest retained singular values and report numerical rank deficiency explicitly.', example:'[[1,0],[0,0.001]]', aliases:['condition number','kappa 2','conditioning'] },
  { id:'conjugate-gradient', operation:'conjugate-gradient', label:'Conjugate-gradient solve', category:'Linear Algebra', phase:'E5', objectKinds:['matrix'], description:'Solve a symmetric positive-definite augmented system [A|b] iteratively with residual-based stopping diagnostics.', example:'[[4,1,1],[1,3,2]]', aliases:['CG','conjugate gradient','iterative SPD solve'] },
  { id:'nonlinear-system-solve', operation:'nonlinear-system-solve', label:'Nonlinear system Newton', category:'Numerical Math & ODEs', phase:'E5', objectKinds:['function'], description:'Solve a square 2–6 variable nonlinear system locally with damped multivariate Newton and a numerical Jacobian.', example:'F(x,y) := [x^2 + y^2 - 1, x-y]', aliases:['nonlinear equations','multivariate Newton','Newton system'] },
  { id:'numerical-optimize', operation:'numerical-optimize', label:'Numerical local optimization', category:'Numerical Math & ODEs', phase:'E5', objectKinds:['function','expression'], description:'Minimize a scalar 2–6 variable objective locally with gradient descent, Newton, or BFGS plus backtracking.', example:'f(x,y) := (x-1)^2 + 2*(y+2)^2', aliases:['optimization','BFGS','gradient descent','Newton optimization'] },
  { id:'constrained-optimize', operation:'constrained-optimize', label:'Equality-constrained optimization', category:'Numerical Math & ODEs', phase:'E5', objectKinds:['function','expression'], description:'Minimize a scalar objective locally under one equality constraint using bounded quadratic-penalty stages.', example:'f(x,y) := x^2 + y^2', aliases:['constraint','penalty method','equality constrained'] },
  { id:'convexity-diagnostic', operation:'convexity-diagnostic', label:'Convexity / Hessian diagnostic', category:'Numerical Math & ODEs', phase:'E5', objectKinds:['function','expression'], description:'Inspect Hessian curvature; constant Hessians permit a global numerical sign classification while variable Hessians remain pointwise/local.', example:'f(x,y) := x^2 + 2*y^2 + x*y', aliases:['convexity','Hessian','concavity','curvature'] },
  { id:'linear-program', operation:'linear-program', label:'Bounded 2D linear program', category:'Numerical Math & ODEs', phase:'E5', objectKinds:['matrix'], description:'Optimize a linear objective over a bounded two-variable polygon encoded by rows [a,b,c] meaning ax+by≤c, with x,y≥0 implicit.', example:'[[1,0,4],[0,1,3],[1,1,5]]', aliases:['linear programming','LP','vertex enumeration'] },
];
