import type { ToolCatalogItem } from './toolCatalog';

const p='Probability & Statistics' as const;
export const E6_TOOL_CATALOG:ToolCatalogItem[]=[
{id:'e6-advanced-distributions',operation:'distribution-profile',label:'Advanced continuous distributions',category:p,phase:'E6',objectKinds:['distribution'],description:'Profile exponential, chi-square, Student-t, and F distributions with numerical special-function probability and quantile workflows.',example:'studentt(10)',aliases:['student t','chi square','exponential','F distribution']},
{id:'joint-distribution-profile',operation:'joint-distribution-profile',label:'Joint PMF, marginals & covariance',category:p,phase:'E6',objectKinds:['distribution'],description:'Analyze a finite joint probability table, marginals, expectations, covariance, and correlation.',example:'jointpmf([[1/4,1/4],[1/8,3/8]])',aliases:['joint distribution','joint pmf','marginal','covariance']},
{id:'affine-rv-transform',operation:'affine-rv-transform',label:'Affine random-variable transform',category:p,phase:'E6',objectKinds:['distribution'],description:'Propagate expectation and variance through Y=aX+b for supported univariate distributions.',example:'normal(10,2)',aliases:['random variable transformation','linear transform','expectation variance']},
{id:'covariance-correlation-matrix',operation:'covariance-correlation-matrix',label:'Covariance & correlation matrices',category:p,phase:'E6',objectKinds:['matrix'],description:'Treat matrix columns as variables and compute sample covariance and Pearson correlation matrices.',example:'[[1,2,5],[2,4,4],[3,5,2],[4,8,1]]',aliases:['covariance matrix','correlation matrix','multivariate statistics']},
{id:'two-sample-mean-inference',operation:'two-sample-mean-inference',label:'Welch two-sample inference',category:p,phase:'E6',objectKinds:['matrix'],description:'Compare two sample means using Welch t inference and a confidence interval without assuming equal variances.',example:'[[8,5],[9,6],[10,7],[11,7],[12,8]]',aliases:['two sample t test','Welch test','difference of means']},
{id:'paired-mean-inference',operation:'paired-mean-inference',label:'Paired-sample inference',category:p,phase:'E6',objectKinds:['matrix'],description:'Analyze matched row pairs through one-sample t inference on within-pair differences.',example:'[[10,8],[12,11],[9,8],[14,12],[13,11]]',aliases:['paired t test','matched pairs']},
{id:'two-proportion-inference',operation:'two-proportion-inference',label:'Two-proportion inference',category:p,phase:'E6',objectKinds:['matrix'],description:'Compare two binary sample proportions with pooled z testing and an explicit approximate interval.',example:'[[1,1],[1,0],[1,1],[0,0],[1,0],[0,1],[1,1],[1,0]]',aliases:['two proportion z test','difference proportions']},
{id:'chi-square-goodness',operation:'chi-square-goodness',label:'Chi-square goodness of fit',category:p,phase:'E6',objectKinds:['vector','dataset'],description:'Compare observed category counts with configured expected counts or proportions.',example:'[18,22,20,40]',aliases:['goodness of fit','categorical test','chi squared']},
{id:'chi-square-independence',operation:'chi-square-independence',label:'Chi-square independence',category:p,phase:'E6',objectKinds:['matrix'],description:'Analyze a contingency table with expected counts, chi-square p-value, and Cramér’s V.',example:'[[20,30],[35,15]]',aliases:['contingency table','independence test','Cramers V']},
{id:'one-way-anova',operation:'one-way-anova',label:'One-way ANOVA',category:p,phase:'E6',objectKinds:['matrix'],description:'Compare equal-sized group columns using the classical one-way F test and eta-squared effect size.',example:'[[8,11,15],[9,12,14],[10,13,16],[9,12,17]]',aliases:['ANOVA','F test','group means']},
{id:'multiple-linear-regression',operation:'multiple-linear-regression',label:'Multiple linear regression',category:p,phase:'E6',objectKinds:['matrix'],description:'Fit ordinary least squares with predictor columns followed by the response, including coefficient inference and adjusted R².',example:'[[1,2,5],[2,1,6],[3,4,10],[4,3,11],[5,5,15],[6,4,16]]',aliases:['OLS','multiple regression','linear model']},
{id:'regression-diagnostics',operation:'regression-diagnostics',label:'Regression diagnostics',category:p,phase:'E6',objectKinds:['matrix'],description:'Inspect standardized residuals, leverage, Cook’s distance, and variance-inflation factors for an OLS design.',example:'[[1,2,5],[2,1,6],[3,4,10],[4,3,11],[5,5,15],[6,4,16]]',aliases:['Cook distance','leverage','VIF','residual diagnostics']},
{id:'mann-whitney',operation:'mann-whitney',label:'Mann–Whitney U test',category:p,phase:'E6',objectKinds:['matrix'],description:'Run a two-sample rank test with tie correction and an explicit normal-approximation p-value.',example:'[[1,4],[2,5],[2,6],[3,8],[4,9]]',aliases:['Wilcoxon rank sum','nonparametric two sample']},
{id:'wilcoxon-signed-rank',operation:'wilcoxon-signed-rank',label:'Wilcoxon signed-rank test',category:p,phase:'E6',objectKinds:['matrix'],description:'Analyze paired differences with signed ranks and an explicit approximate p-value.',example:'[[10,8],[12,11],[9,8],[14,12],[13,11]]',aliases:['paired nonparametric','signed rank']},
{id:'bootstrap-mean',operation:'bootstrap-mean',label:'Bootstrap mean interval',category:p,phase:'E6',objectKinds:['vector','dataset'],description:'Build a deterministic seeded percentile bootstrap interval for the sample mean.',example:'data(4,5,6,7,9,10)',aliases:['resampling','percentile bootstrap','bootstrap CI']},
{id:'markov-profile',operation:'markov-profile',label:'Finite Markov-chain profile',category:p,phase:'E6',objectKinds:['matrix'],description:'Validate a row-stochastic transition matrix and estimate a stationary distribution with irreducibility diagnostics.',example:'[[0.8,0.2],[0.3,0.7]]',aliases:['Markov chain','transition matrix','stationary distribution']},
{id:'markov-step',operation:'markov-step',label:'Markov state propagation',category:p,phase:'E6',objectKinds:['matrix'],description:'Propagate a configured probability vector through a finite transition matrix for a selected number of steps.',example:'[[0.8,0.2],[0.3,0.7]]',aliases:['Markov step','state distribution','transition']},
];
