import type { ToolCatalogItem } from './toolCatalog';

const analysis = 'Analysis' as const;
const numerical = 'Numerical Math & ODEs' as const;

export const E7_TOOL_CATALOG: ToolCatalogItem[] = [
  { id:'laplace-transform', operation:'laplace-transform', label:'Laplace transform', category:analysis, phase:'E7', objectKinds:['expression','function'], description:'Apply the verified unilateral Laplace table with linearity and supported exponential-shift rules.', example:'f(t) := t^2 + 3*sin(2*t)', aliases:['Laplace','integral transform','s domain'] },
  { id:'inverse-laplace-transform', operation:'inverse-laplace-transform', label:'Inverse Laplace transform', category:analysis, phase:'E7', objectKinds:['expression','function'], description:'Invert supported linear combinations and proper rational transforms with denominator degree at most two.', example:'1/(s^2+1)', aliases:['inverse Laplace','time domain','rational transform'] },
  { id:'convolution', operation:'convolution', label:'Convolution theorem', category:analysis, phase:'E7', objectKinds:['expression','function'], description:'Form the unilateral convolution and multiply exact Laplace transforms, reconstructing a closed form when the bounded inverse table permits.', example:'f(t) := exp(-t)', aliases:['convolution','convolution theorem','f*g'] },
  { id:'laplace-ode-solve', operation:'laplace-ode-solve', label:'Solve ODE by Laplace transform', category:numerical, phase:'E7', objectKinds:['ode'], description:'Solve a constant-coefficient second-order initial-value problem in the s-domain and invert when the supported rational table closes.', example:'ode2(1,0,1,0,0,1,0)', aliases:['Laplace ODE','transform ODE','initial value problem'] },
  { id:'fourier-series', operation:'fourier-series', label:'Fourier series coefficients', category:analysis, phase:'E7', objectKinds:['expression','function'], description:'Approximate Fourier coefficients on one configured period with structural even/odd coefficient elimination.', example:'f(t) := t', aliases:['Fourier series','harmonics','coefficients','even odd'] },
  { id:'fourier-transform', operation:'fourier-transform', label:'Exact Fourier transform', category:analysis, phase:'E7', objectKinds:['expression','function'], description:'Apply the certified bilateral angular-frequency Fourier table. E7 begins with exact Gaussian transforms rather than distribution-valued guesses.', example:'f(t) := exp(-t^2)', aliases:['Fourier transform','Gaussian transform','frequency domain'] },
  { id:'inverse-fourier-transform', operation:'inverse-fourier-transform', label:'Exact inverse Fourier transform', category:analysis, phase:'E7', objectKinds:['expression','function'], description:'Apply the bounded exact inverse bilateral Fourier table under the 1/(2π) convention.', example:'F(omega) := exp(-omega^2)', aliases:['inverse Fourier','Gaussian inverse','time domain'] },
  { id:'numerical-fourier-transform', operation:'numerical-fourier-transform', label:'Numerical Fourier evaluation', category:analysis, phase:'E7', objectKinds:['expression','function'], description:'Evaluate a finite-window Fourier integral at one angular frequency using deterministic composite Simpson quadrature.', example:'f(t) := exp(-t^2)', aliases:['numerical Fourier','frequency evaluation','quadrature'] },
  { id:'numerical-inverse-fourier-transform', operation:'numerical-inverse-fourier-transform', label:'Numerical inverse Fourier evaluation', category:analysis, phase:'E7', objectKinds:['expression','function'], description:'Evaluate a finite frequency-window inverse Fourier integral at one time point with explicit truncation error boundaries.', example:'F(omega) := exp(-omega^2)', aliases:['numerical inverse Fourier','inverse quadrature'] },
  { id:'discrete-fourier-transform', operation:'discrete-fourier-transform', label:'Discrete Fourier transform', category:analysis, phase:'E7', objectKinds:['vector'], description:'Compute a bounded direct O(N²) DFT for 2–256 resolved real samples and expose complex bins and magnitudes.', example:'[1,0,-1,0]', aliases:['DFT','discrete transform','spectrum'] },
  { id:'inverse-discrete-fourier-transform', operation:'inverse-discrete-fourier-transform', label:'Inverse discrete Fourier transform', category:analysis, phase:'E7', objectKinds:['matrix'], description:'Reconstruct samples from an n×2 [real, imaginary] coefficient matrix with the standard 1/N inverse normalization.', example:'[[0,0],[2,0],[0,0],[2,0]]', aliases:['IDFT','inverse DFT','reconstruction'] },
];
