import type { ToolCatalogItem } from './toolCatalog';

const a = 'Analysis' as const;
export const E8_TOOL_CATALOG: ToolCatalogItem[] = [
  { id: 'complex-map', operation: 'complex-map', label: 'Complex point mapping', category: a, phase: 'E8', objectKinds: ['expression','function'], description: 'Evaluate a unary complex expression at z=a+bi, reporting rectangular/polar output and a local derivative signal when available.', example: 'f(z) := z^2 + 1', aliases: ['complex mapping','complex evaluate','conformal map'] },
  { id: 'complex-decompose', operation: 'complex-decompose', label: 'Real / imaginary decomposition', category: a, phase: 'E8', objectKinds: ['expression','function'], description: 'Substitute z=x+iy and derive exact u(x,y), v(x,y) for supported complex arithmetic and elementary forms.', example: 'f(z) := z^3 + 2*z', aliases: ['real part','imaginary part','u v decomposition'] },
  { id: 'complex-derivative', operation: 'complex-derivative', label: 'Complex derivative', category: a, phase: 'E8', objectKinds: ['expression','function'], description: 'Differentiate supported holomorphic elementary expressions exactly, with explicit branch-domain warnings where needed.', example: 'f(z) := exp(z)*sin(z)', aliases: ['holomorphic derivative','analytic derivative'] },
  { id: 'cauchy-riemann', operation: 'cauchy-riemann', label: 'Cauchy–Riemann check', category: a, phase: 'E8', objectKinds: ['expression','function'], description: 'Derive u and v and certify the Cauchy–Riemann residual identities when exact simplification proves them.', example: 'f(z) := z^2', aliases: ['CR equations','holomorphic check','complex differentiability'] },
  { id: 'complex-series', operation: 'complex-series', label: 'Complex power / Laurent series', category: a, phase: 'E8', objectKinds: ['expression','function'], description: 'Generate an exact local rational power or Laurent expansion around a configured rational real center.', example: 'f(z) := 1/(z*(1-z))', aliases: ['Laurent series','power series','complex series'] },
  { id: 'singularity-profile', operation: 'singularity-profile', label: 'Complex singularity classification', category: a, phase: 'E8', objectKinds: ['expression','function'], description: 'Classify a rational-function point as regular, removable, or a pole of exact order and expose its residue.', example: 'f(z) := (z+1)/z^2', aliases: ['isolated singularity','pole order','removable singularity'] },
  { id: 'complex-residue', operation: 'complex-residue', label: 'Residue at a point', category: a, phase: 'E8', objectKinds: ['expression','function'], description: 'Extract an exact Laurent residue at supported rational real points or use a clearly approximate isolating-circle fallback.', example: 'f(z) := 1/(z*(z+1))', aliases: ['residue','residue coefficient','complex pole'] },
  { id: 'complex-contour-integral', operation: 'complex-contour-integral', label: 'Complex contour integral', category: a, phase: 'E8', objectKinds: ['expression','function'], description: 'Numerically integrate a complex function along a configured circle or line segment with deterministic parameter quadrature.', example: 'f(z) := 1/z', aliases: ['contour integral','path integral','complex line integral'] },
  { id: 'residue-theorem', operation: 'residue-theorem', label: 'Residue theorem on a circle', category: a, phase: 'E8', objectKinds: ['expression','function'], description: 'Discover simple poles of a bounded rational denominator and evaluate a circular contour through 2πi times enclosed residues.', example: 'f(z) := 1/(z^2+1)', aliases: ['residue theorem','poles inside contour','complex integration'] },
  { id: 'branch-diagnostics', operation: 'branch-diagnostics', label: 'Complex branch diagnostics', category: a, phase: 'E8', objectKinds: ['expression','function'], description: 'Identify logarithm, square-root, argument, and non-integer-power branch sensitivity and state principal-branch conventions.', example: 'f(z) := ln(z) + sqrt(z)', aliases: ['branch cut','branch point','principal branch','complex domain'] },
];
