import type { ToolCatalogItem } from './toolCatalog';

const d = 'Discrete Math & Algorithms' as const;
export const E9_TOOL_CATALOG: ToolCatalogItem[] = [
  { id:'finite-quantifier-profile',operation:'finite-quantifier-profile',label:'Finite-domain quantifier',category:d,phase:'E9',objectKinds:['finite-set'],description:'Evaluate a configured universal or existential predicate exhaustively over an explicit finite-set object.',example:'set(-2,-1,0,1,2)',aliases:['forall','exists','quantifier','predicate logic'] },
  { id:'recurrence-generating-function',operation:'recurrence-generating-function',label:'Recurrence generating function',category:d,phase:'E9',objectKinds:['recurrence'],description:'Derive the exact ordinary generating function A(x)=Σa_nx^n for supported first- and second-order linear recurrences.',example:'linrec2(0,1,1,1)',aliases:['generating function','OGF','recurrence series'] },
  { id:'recurrence-closed-form-e9',operation:'recurrence-closed-form-e9',label:'Extended recurrence closed form',category:d,phase:'E9',objectKinds:['recurrence'],description:'Solve supported first- and second-order constant-coefficient recurrences through exact characteristic-root formulas.',example:'linrec2(0,1,1,1)',aliases:['characteristic roots','recurrence solution','closed form'] },
  { id:'extended-master-theorem',operation:'extended-master-theorem',label:'Extended Master theorem',category:d,phase:'E9',objectKinds:['complexity'],description:'Extend master(a,b,k) to toll functions Θ(n^k(log n)^j) with an explicit nonnegative integer log exponent.',example:'master(2,2,1)',aliases:['master theorem','divide conquer','log factor'] },
  { id:'bellman-ford',operation:'bellman-ford',label:'Bellman–Ford shortest path',category:d,phase:'E9',objectKinds:['graph'],description:'Find exact rational shortest paths in weighted graphs with negative edges and detect reachable negative cycles.',example:'wdigraph(4, [[1,2,4],[1,3,5],[2,3,-2],[3,4,3]])',aliases:['negative weight shortest path','bellman ford'] },
  { id:'max-flow-min-cut',operation:'max-flow-min-cut',label:'Maximum flow / minimum cut',category:d,phase:'E9',objectKinds:['graph'],description:'Compute exact max flow by deterministic Edmonds–Karp and expose the equal-capacity residual minimum-cut certificate.',example:'wdigraph(4, [[1,2,3],[1,3,2],[2,3,1],[2,4,2],[3,4,3]])',aliases:['network flow','min cut','edmonds karp'] },
  { id:'bipartite-matching',operation:'bipartite-matching',label:'Maximum bipartite matching',category:d,phase:'E9',objectKinds:['graph'],description:'Certify bipartiteness and compute a deterministic maximum matching through augmenting paths.',example:'graph(6, [[1,4],[1,5],[2,4],[2,6],[3,5]])',aliases:['matching','augmenting path','bipartite'] },
  { id:'longest-increasing-subsequence',operation:'longest-increasing-subsequence',label:'Longest increasing subsequence',category:d,phase:'E9',objectKinds:['vector'],description:'Run an exact O(n²) dynamic program and return one deterministic longest strictly increasing subsequence with its trace.',example:'[3,1,8,2,5]',aliases:['LIS','dynamic programming','subsequence'] },
  { id:'knapsack-dp',operation:'knapsack-dp',label:'0/1 knapsack dynamic program',category:d,phase:'E9',objectKinds:['matrix'],description:'Solve bounded integer-capacity 0/1 knapsack exactly from [weight,value] rows and expose per-item DP progress.',example:'[[2,3],[3,4],[4,5],[5,8]]',aliases:['knapsack','dynamic programming','0/1 dp'] },
  { id:'number-theory-profile',operation:'number-theory-profile',label:'Factorization & arithmetic functions',category:d,phase:'E9',objectKinds:['scalar'],description:'Factor a bounded integer exactly and compute primality, Euler phi, divisor count/sum, and Möbius μ.',example:'360',aliases:['prime factorization','euler phi','totient','divisors','mobius'] },
  { id:'extended-gcd',operation:'extended-gcd',label:'Extended Euclidean algorithm',category:d,phase:'E9',objectKinds:['scalar'],description:'Compute gcd(a,b) with exact Bézout coefficients x,y satisfying ax+by=gcd(a,b).',example:'84',aliases:['egcd','bezout','gcd'] },
  { id:'modular-inverse',operation:'modular-inverse',label:'Modular inverse',category:d,phase:'E9',objectKinds:['scalar'],description:'Find a^(-1) modulo m exactly when gcd(a,m)=1, otherwise fail with the obstruction.',example:'17',aliases:['inverse mod','mod inverse','modular arithmetic'] },
  { id:'linear-congruence',operation:'linear-congruence',label:'Linear congruence solver',category:d,phase:'E9',objectKinds:['scalar'],description:'Solve ax≡b (mod m) exactly, including all residue classes when gcd(a,m)>1 divides b.',example:'6',aliases:['congruence','mod equation','ax=b mod m'] },
  { id:'chinese-remainder',operation:'chinese-remainder',label:'Chinese remainder theorem',category:d,phase:'E9',objectKinds:['matrix'],description:'Merge 1–20 congruences exactly, including compatible non-coprime moduli, and return the canonical combined class.',example:'[[2,3],[3,5],[2,7]]',aliases:['CRT','simultaneous congruences','mod system'] },
  { id:'linear-diophantine',operation:'linear-diophantine',label:'Linear Diophantine equation',category:d,phase:'E9',objectKinds:['scalar'],description:'Solve ax+by=c over integers and return one solution plus the complete one-parameter family.',example:'15',aliases:['diophantine','integer equation','bezout equation'] },
];
