import type { AstNode } from './ast';
import { rationalValue, simplifyAst } from './algebra';
import { parseMath } from './parser';
import { rationalToNumber } from './rational';
import type { MathResultFact, MathResultSection } from './types';

export interface E6Transform {
  ast?: AstNode;
  display: string;
  exactness: 'exact'|'approximate'|'heuristic';
  warnings: string[];
  sections: MathResultSection[];
}

type Matrix=number[][];
type Vector=number[];
export type E6DistributionFamily='exponential'|'chisquare'|'studentt'|'fdist';
const E6_DISTRIBUTIONS=new Set<E6DistributionFamily>(['exponential','chisquare','studentt','fdist']);

function n(value:number|string):AstNode{return{type:'number',value:String(value)};}
function vectorAst(values:Vector):AstNode{return{type:'matrix',rows:[values.map(v=>n(clean(v)))]};}
function matrixAst(values:Matrix):AstNode{return{type:'matrix',rows:values.map(row=>row.map(v=>n(clean(v))))};}
function section(id:string,title:string,facts:MathResultFact[],description?:string):MathResultSection{return{id,title,facts,description};}
function fixed(value:number,digits=8):string{if(!Number.isFinite(value))return String(value);const a=Math.abs(value);if((a>0&&a<1e-6)||a>=1e9)return value.toExponential(6);return Number(value.toFixed(digits)).toString();}
function clean(value:number):number{return Math.abs(value)<1e-14?0:value;}
function clamp01(value:number):number{return Math.max(0,Math.min(1,value));}
function mean(x:Vector):number{return x.reduce((a,b)=>a+b,0)/x.length;}
function sampleVariance(x:Vector):number{if(x.length<2)throw new Error('Sample variance requires at least two observations.');const m=mean(x);return x.reduce((s,v)=>s+(v-m)**2,0)/(x.length-1);}
function dot(a:Vector,b:Vector):number{return a.reduce((s,v,i)=>s+v*b[i],0);}
function transpose(A:Matrix):Matrix{return Array.from({length:A[0].length},(_,j)=>A.map(r=>r[j]));}
function matmul(A:Matrix,B:Matrix):Matrix{return A.map(row=>Array.from({length:B[0].length},(_,j)=>row.reduce((s,v,k)=>s+v*B[k][j],0)));}
function matvec(A:Matrix,x:Vector):Vector{return A.map(row=>dot(row,x));}
function identity(size:number):Matrix{return Array.from({length:size},(_,i)=>Array.from({length:size},(_,j)=>i===j?1:0));}

function numericCell(node:AstNode,label='value'):number{const r=rationalValue(simplifyAst(node));if(!r)throw new Error(`${label} must resolve to a finite real number.`);const v=rationalToNumber(r);if(!Number.isFinite(v))throw new Error(`${label} must be finite.`);return v;}
function numericMatrix(node:AstNode):Matrix{const ast=node.type==='definition'?node.right:node;if(ast.type!=='matrix'||!ast.rows.length||!ast.rows[0]?.length)throw new Error('This E6 workflow requires a numeric matrix.');const cols=ast.rows[0].length;if(ast.rows.some(row=>row.length!==cols))throw new Error('Matrix rows must have equal length.');if(ast.rows.length>5000||cols>30)throw new Error('E6 statistical matrix workflows are bounded to 5000 observations and 30 columns.');return ast.rows.map((row,i)=>row.map((cell,j)=>numericCell(cell,`matrix entry (${i+1},${j+1})`)));}
function datasetVector(node:AstNode):Vector{const ast=node.type==='definition'?node.right:node;if(ast.type==='call'&&ast.name==='data')return ast.args.map((cell,i)=>numericCell(cell,`observation ${i+1}`));if(ast.type==='matrix'&&ast.rows.length===1)return ast.rows[0].map((cell,i)=>numericCell(cell,`observation ${i+1}`));throw new Error('This workflow expects data(...) or a numeric vector.');}
function parseVector(source:string|undefined,label:string):Vector{if(!source?.trim())throw new Error(`${label} is required.`);const p=parseMath(source);if(!p.ast||p.diagnostics.some(d=>d.severity==='error'))throw new Error(`${label} must be a numeric vector.`);const ast=p.ast.type==='definition'?p.ast.right:p.ast;if(ast.type!=='matrix'||ast.rows.length!==1)throw new Error(`${label} must be a vector such as [0.5, 0.5].`);return ast.rows[0].map((cell,i)=>numericCell(cell,`${label} entry ${i+1}`));}
function parseScalar(source:string|undefined,label:string):number{if(!source?.trim())throw new Error(`${label} is required.`);const p=parseMath(source);if(!p.ast||p.diagnostics.some(d=>d.severity==='error'))throw new Error(`${label} must be numeric.`);return numericCell(p.ast,label);}

function gaussianSolve(A0:Matrix,b0:Vector):Vector{const A=A0.map(r=>[...r]),b=[...b0],size=A.length;if(A.some(r=>r.length!==size)||b.length!==size)throw new Error('Linear solve requires a square system.');for(let k=0;k<size;k++){let p=k;for(let i=k+1;i<size;i++)if(Math.abs(A[i][k])>Math.abs(A[p][k]))p=i;if(Math.abs(A[p][k])<1e-12)throw new Error('Statistical normal equations are singular or numerically rank deficient.');[A[k],A[p]]=[A[p],A[k]];[b[k],b[p]]=[b[p],b[k]];for(let i=k+1;i<size;i++){const f=A[i][k]/A[k][k];for(let j=k;j<size;j++)A[i][j]-=f*A[k][j];b[i]-=f*b[k];}}const x=Array(size).fill(0);for(let i=size-1;i>=0;i--){let s=b[i];for(let j=i+1;j<size;j++)s-=A[i][j]*x[j];x[i]=s/A[i][i];}return x;}
function inverse(A:Matrix):Matrix{const size=A.length;if(A.some(r=>r.length!==size))throw new Error('Inverse requires a square matrix.');const aug=A.map((row,i)=>[...row,...identity(size)[i]]);for(let k=0;k<size;k++){let p=k;for(let i=k+1;i<size;i++)if(Math.abs(aug[i][k])>Math.abs(aug[p][k]))p=i;if(Math.abs(aug[p][k])<1e-12)throw new Error('Matrix is singular or numerically rank deficient.');[aug[k],aug[p]]=[aug[p],aug[k]];const pivot=aug[k][k];aug[k]=aug[k].map(v=>v/pivot);for(let i=0;i<size;i++)if(i!==k){const f=aug[i][k];aug[i]=aug[i].map((v,j)=>v-f*aug[k][j]);}}return aug.map(row=>row.slice(size));}

function logGamma(z:number):number{const p=[0.9999999999998099,676.5203681218851,-1259.1392167224028,771.3234287776531,-176.6150291621406,12.507343278686905,-0.13857109526572012,9.984369578019572e-6,1.5056327351493116e-7];if(z<0.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-logGamma(1-z);z-=1;let x=p[0];for(let i=1;i<p.length;i++)x+=p[i]/(z+i);const t=z+7.5;return 0.5*Math.log(2*Math.PI)+(z+0.5)*Math.log(t)-t+Math.log(x);}
function gammaP(a:number,x:number):number{if(!(a>0)||x<0)return NaN;if(x===0)return 0;if(x<a+1){let ap=a,sum=1/a,del=sum;for(let i=1;i<=200;i++){ap++;del*=x/ap;sum+=del;if(Math.abs(del)<Math.abs(sum)*1e-14)break;}return clamp01(sum*Math.exp(-x+a*Math.log(x)-logGamma(a)));}let b=x+1-a,c=1/1e-300,d=1/b,h=d;for(let i=1;i<=200;i++){const an=-i*(i-a);b+=2;d=an*d+b;if(Math.abs(d)<1e-300)d=1e-300;c=b+an/c;if(Math.abs(c)<1e-300)c=1e-300;d=1/d;const del=d*c;h*=del;if(Math.abs(del-1)<1e-14)break;}return clamp01(1-Math.exp(-x+a*Math.log(x)-logGamma(a))*h);}
function betaCf(a:number,b:number,x:number):number{const max=200,eps=3e-14,fpmin=1e-300;let qab=a+b,qap=a+1,qam=a-1,c=1,d=1-qab*x/qap;if(Math.abs(d)<fpmin)d=fpmin;d=1/d;let h=d;for(let m=1;m<=max;m++){const m2=2*m;let aa=m*(b-m)*x/((qam+m2)*(a+m2));d=1+aa*d;if(Math.abs(d)<fpmin)d=fpmin;c=1+aa/c;if(Math.abs(c)<fpmin)c=fpmin;d=1/d;h*=d*c;aa=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa*d;if(Math.abs(d)<fpmin)d=fpmin;c=1+aa/c;if(Math.abs(c)<fpmin)c=fpmin;d=1/d;const del=d*c;h*=del;if(Math.abs(del-1)<eps)break;}return h;}
function regBeta(x:number,a:number,b:number):number{if(x<=0)return 0;if(x>=1)return 1;const bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log(1-x));return x<(a+1)/(a+b+2)?bt*betaCf(a,b,x)/a:1-bt*betaCf(b,a,1-x)/b;}
function erf(x:number):number{const sign=x<0?-1:1,z=Math.abs(x),t=1/(1+0.3275911*z);const y=1-(((((1.061405429*t-1.453152027)*t+1.421413741)*t-0.284496736)*t+0.254829592)*t)*Math.exp(-z*z);return sign*y;}
function normalCdf(x:number):number{return 0.5*(1+erf(x/Math.SQRT2));}
function studentTCdf(t:number,df:number):number{const x=df/(df+t*t),ib=regBeta(x,df/2,0.5);return t>=0?1-0.5*ib:0.5*ib;}
function fCdf(x:number,d1:number,d2:number):number{return x<=0?0:regBeta((d1*x)/(d1*x+d2),d1/2,d2/2);}
function chiSquareCdf(x:number,df:number):number{return x<=0?0:gammaP(df/2,x/2);}
function twoSidedFromCdf(stat:number,cdf:(x:number)=>number):number{return clamp01(2*Math.min(cdf(stat),1-cdf(stat)));}
function quantileByCdf(p:number,cdf:(x:number)=>number,lo:number,hi:number):number{if(!(p>0&&p<1))throw new Error('Quantile probability must satisfy 0 < p < 1.');let left=lo,right=hi;while(cdf(right)<p&&right<1e12)right=right*2+1;while(cdf(left)>p&&left>-1e12)left=left*2-1;for(let i=0;i<140;i++){const mid=(left+right)/2;if(cdf(mid)<p)left=mid;else right=mid;}return(left+right)/2;}

interface DistSpec{family:E6DistributionFamily;args:number[];}
export function isE6DistributionCall(node:AstNode):boolean{return node.type==='call'&&E6_DISTRIBUTIONS.has(node.name as E6DistributionFamily);}
function distSpec(node:AstNode):DistSpec{const ast=node.type==='definition'?node.right:simplifyAst(node);if(ast.type!=='call'||!E6_DISTRIBUTIONS.has(ast.name as E6DistributionFamily))throw new Error('Expected exponential(lambda), chisquare(df), studentt(df), or fdist(df1,df2).');const family=ast.name as E6DistributionFamily,args=ast.args.map((a,i)=>numericCell(a,`distribution parameter ${i+1}`));if(family==='exponential'&&(args.length!==1||!(args[0]>0)))throw new Error('exponential(lambda) requires lambda > 0.');if((family==='chisquare'||family==='studentt')&&(args.length!==1||!(args[0]>0)))throw new Error(`${family}(df) requires df > 0.`);if(family==='fdist'&&(args.length!==2||!(args[0]>0)||!(args[1]>0)))throw new Error('fdist(df1,df2) requires positive degrees of freedom.');return{family,args};}
function distMoments(spec:DistSpec):{mean:number;variance:number;support:string}{const a=spec.args;if(spec.family==='exponential')return{mean:1/a[0],variance:1/(a[0]*a[0]),support:'[0, ∞)'};if(spec.family==='chisquare')return{mean:a[0],variance:2*a[0],support:'[0, ∞)'};if(spec.family==='studentt')return{mean:a[0]>1?0:NaN,variance:a[0]>2?a[0]/(a[0]-2):a[0]>1?Infinity:NaN,support:'(-∞, ∞)'};const d1=a[0],d2=a[1];return{mean:d2>2?d2/(d2-2):Infinity,variance:d2>4?2*d2*d2*(d1+d2-2)/(d1*(d2-2)**2*(d2-4)):Infinity,support:'[0, ∞)'};}
function distCdf(spec:DistSpec,x:number):number{if(spec.family==='exponential')return x<=0?0:1-Math.exp(-spec.args[0]*x);if(spec.family==='chisquare')return chiSquareCdf(x,spec.args[0]);if(spec.family==='studentt')return studentTCdf(x,spec.args[0]);return fCdf(x,spec.args[0],spec.args[1]);}
export function advancedDistributionProfile(node:AstNode):E6Transform{const spec=distSpec(node),m=distMoments(spec);return{ast:n(clean(m.mean)),display:`${spec.family}(${spec.args.map(v=>fixed(v)).join(', ')})`,exactness:'approximate',warnings:['E6 reports special-function distribution moments/CDF workflows numerically in binary64; the mathematical formulas remain standard analytic definitions.'],sections:[section('e6-distribution','E6 distribution profile',[{label:'Family',display:spec.family},{label:'Support',display:m.support},{label:'Expectation',display:fixed(m.mean)},{label:'Variance',display:fixed(m.variance)},{label:'Standard deviation',display:fixed(Math.sqrt(m.variance))}]) ]};}
export function advancedDistributionProbability(node:AstNode,event:string,value?:string,lower?:string,upper?:string):E6Transform{const spec=distSpec(node);let p:number,label:string;if(event==='between'){const a=parseScalar(lower,'Lower bound'),b=parseScalar(upper,'Upper bound');if(a>b)throw new Error('Lower bound must not exceed upper bound.');p=distCdf(spec,b)-distCdf(spec,a);label=`P(${fixed(a)} ≤ X ≤ ${fixed(b)})`;}else{const x=parseScalar(value,'Event value');if(event==='le'){p=distCdf(spec,x);label=`P(X ≤ ${fixed(x)})`;}else if(event==='ge'){p=1-distCdf(spec,x);label=`P(X ≥ ${fixed(x)})`;}else throw new Error('Continuous E6 distributions do not have positive point mass; use ≤, ≥, or between.');}return{ast:n(clean(p)),display:fixed(p,10),exactness:'approximate',warnings:['Probability is evaluated numerically through regularized gamma/beta or elementary CDF formulas.'],sections:[section('e6-probability','Distribution probability',[{label:'Event',display:label},{label:'Probability',display:fixed(p,12),tone:'positive'}]) ]};}
export function advancedDistributionQuantile(node:AstNode,probability:string):E6Transform{const spec=distSpec(node),p=parseScalar(probability,'Probability');let q:number;if(spec.family==='exponential')q=-Math.log(1-p)/spec.args[0];else if(spec.family==='studentt')q=quantileByCdf(p,x=>distCdf(spec,x),-1,1);else q=quantileByCdf(p,x=>distCdf(spec,x),0,Math.max(1,distMoments(spec).mean));return{ast:n(clean(q)),display:fixed(q,10),exactness:'approximate',warnings:['Quantiles use deterministic numerical inversion of the E6 CDF.'],sections:[section('e6-quantile','Distribution quantile',[{label:'p',display:fixed(p)},{label:'Quantile',display:fixed(q,12),tone:'positive'}]) ]};}
export function advancedSamplingMean(node:AstNode,sampleSize:number):E6Transform{if(!Number.isInteger(sampleSize)||sampleSize<1)throw new Error('Sample size must be a positive integer.');const spec=distSpec(node),m=distMoments(spec);if(!Number.isFinite(m.mean)||!Number.isFinite(m.variance))throw new Error('Sampling-mean moments require finite distribution mean and variance.');const se=Math.sqrt(m.variance/sampleSize);return{display:`E[X̄]≈${fixed(m.mean)} · SE≈${fixed(se)}`,exactness:'approximate',warnings:[sampleSize<30?'The normal sampling-distribution approximation may be poor for a small non-normal sample.':'The normal approximation is justified asymptotically by the central limit theorem, not as an exact finite-sample law.'],sections:[section('e6-sampling','Sampling distribution of the mean',[{label:'n',display:String(sampleSize)},{label:'E[X̄]',display:fixed(m.mean)},{label:'Var(X̄)',display:fixed(m.variance/sampleSize)},{label:'SE(X̄)',display:fixed(se)}]) ]};}

function rng(seed:number):()=>number{let x=(seed|0)||0x6d2b79f5;return()=>{x|=0;x=x+0x6d2b79f5|0;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function normalDraw(random:()=>number):number{const u=Math.max(random(),1e-12),v=random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);}
function gammaDraw(shape:number,scale:number,random:()=>number):number{if(shape<1)return gammaDraw(shape+1,scale,random)*random()**(1/shape);const d=shape-1/3,c=1/Math.sqrt(9*d);for(;;){let x=normalDraw(random),v=1+c*x;if(v<=0)continue;v=v**3;const u=random();if(u<1-0.0331*x**4||Math.log(u)<0.5*x*x+d*(1-v+Math.log(v)))return d*v*scale;}}
function drawDist(spec:DistSpec,random:()=>number):number{if(spec.family==='exponential')return-Math.log(Math.max(random(),1e-12))/spec.args[0];if(spec.family==='chisquare')return gammaDraw(spec.args[0]/2,2,random);if(spec.family==='studentt'){const z=normalDraw(random),v=gammaDraw(spec.args[0]/2,2,random);return z/Math.sqrt(v/spec.args[0]);}const x=gammaDraw(spec.args[0]/2,2,random)/spec.args[0],y=gammaDraw(spec.args[1]/2,2,random)/spec.args[1];return x/y;}
export function simulateAdvancedDistribution(node:AstNode,count:number,seed:number):E6Transform{if(!Number.isInteger(count)||count<1||count>10000)throw new Error('Simulation count must be an integer from 1 to 10000.');const spec=distSpec(node),random=rng(seed),draws=Array.from({length:count},()=>drawDist(spec,random)),m=mean(draws);return{display:`${count} deterministic draws · mean≈${fixed(m)}`,exactness:'heuristic',warnings:['Simulation is pseudorandom numerical evidence, not an exact probability calculation. The seed makes the experiment reproducible.'],sections:[section('e6-simulation','Distribution simulation',[{label:'Draws',display:String(count)},{label:'Seed',display:String(seed)},{label:'Sample mean',display:fixed(m)},{label:'First 10 draws',display:draws.slice(0,10).map(v=>fixed(v,5)).join(', ')}]) ]};}

function jointTable(node:AstNode):Matrix{const ast=node.type==='definition'?node.right:node;if(ast.type!=='call'||ast.name!=='jointpmf'||ast.args.length!==1||ast.args[0].type!=='matrix')throw new Error('Joint distributions use jointpmf([[p00,p01,...],[p10,...]]).');const table=numericMatrix(ast.args[0]);if(table.some(row=>row.some(v=>v<0)))throw new Error('Joint PMF entries must be nonnegative.');const total=table.flat().reduce((s,v)=>s+v,0);if(Math.abs(total-1)>1e-10)throw new Error(`Joint PMF entries must sum to 1; received ${fixed(total,12)}.`);return table;}
export function jointDistributionProfile(node:AstNode):E6Transform{const P=jointTable(node),rows=P.length,cols=P[0].length,px=P.map(r=>r.reduce((s,v)=>s+v,0)),py=Array.from({length:cols},(_,j)=>P.reduce((s,r)=>s+r[j],0)),ex=px.reduce((s,p,i)=>s+i*p,0),ey=py.reduce((s,p,j)=>s+j*p,0),exy=P.reduce((s,row,i)=>s+row.reduce((t,p,j)=>t+i*j*p,0),0),vx=px.reduce((s,p,i)=>s+(i-ex)**2*p,0),vy=py.reduce((s,p,j)=>s+(j-ey)**2*p,0),cov=exy-ex*ey,corr=vx>0&&vy>0?cov/Math.sqrt(vx*vy):NaN;return{ast:matrixAst(P),display:`E[X]=${fixed(ex)} · E[Y]=${fixed(ey)} · Cov=${fixed(cov)}`,exactness:'approximate',warnings:['jointpmf uses zero-based support indices: row i represents X=i and column j represents Y=j. Use an explicitly transformed variable if your support uses different numeric labels.'],sections:[section('joint','Joint discrete distribution',[{label:'Shape',display:`${rows}×${cols}`},{label:'X marginal',display:`[${px.map(v=>fixed(v)).join(', ')}]`,ast:vectorAst(px)},{label:'Y marginal',display:`[${py.map(v=>fixed(v)).join(', ')}]`,ast:vectorAst(py)},{label:'E[X]',display:fixed(ex)},{label:'E[Y]',display:fixed(ey)},{label:'Cov(X,Y)',display:fixed(cov)},{label:'Corr(X,Y)',display:fixed(corr)}]) ]};}

function genericMoments(node:AstNode):{mean:number;variance:number;family:string}{const ast=node.type==='definition'?node.right:node;if(isE6DistributionCall(ast)){const spec=distSpec(ast),m=distMoments(spec);return{mean:m.mean,variance:m.variance,family:spec.family};}if(ast.type!=='call')throw new Error('Affine random-variable transforms require a supported univariate distribution.');const args=ast.args.map((a,i)=>numericCell(a,`distribution parameter ${i+1}`));if(ast.name==='bernoulli')return{mean:args[0],variance:args[0]*(1-args[0]),family:ast.name};if(ast.name==='binomial')return{mean:args[0]*args[1],variance:args[0]*args[1]*(1-args[1]),family:ast.name};if(ast.name==='geometric')return{mean:1/args[0],variance:(1-args[0])/(args[0]**2),family:ast.name};if(ast.name==='poisson')return{mean:args[0],variance:args[0],family:ast.name};if(ast.name==='uniform')return{mean:(args[0]+args[1])/2,variance:(args[1]-args[0])**2/12,family:ast.name};if(ast.name==='normal')return{mean:args[0],variance:args[1]**2,family:ast.name};throw new Error('Affine transform supports P10 and E6 univariate distribution families.');}
export function affineRandomVariable(node:AstNode,scale:number,shift:number):E6Transform{if(!Number.isFinite(scale)||!Number.isFinite(shift))throw new Error('Affine transform coefficients must be finite.');const m=genericMoments(node),mu=scale*m.mean+shift,v=scale*scale*m.variance;return{ast:vectorAst([mu,v]),display:`Y=${fixed(scale)}X+${fixed(shift)} · E[Y]≈${fixed(mu)}`,exactness:'approximate',warnings:['The affine moment identities are exact; displayed decimal moments are binary64 approximations.'],sections:[section('affine-rv','Affine random-variable transform',[{label:'Source family',display:m.family},{label:'Transform',display:`Y = ${fixed(scale)}X + ${fixed(shift)}`},{label:'E[Y]',display:fixed(mu)},{label:'Var(Y)',display:fixed(v)},{label:'SD(Y)',display:fixed(Math.sqrt(v))}]) ]};}

export function covarianceCorrelationMatrix(node:AstNode):E6Transform{const A=numericMatrix(node),obs=A.length,k=A[0].length;if(obs<2||k<2)throw new Error('Covariance matrices require at least two observations and two variables (columns).');const columns=transpose(A),means=columns.map(mean),cov=Array.from({length:k},(_,i)=>Array.from({length:k},(_,j)=>A.reduce((s,row)=>s+(row[i]-means[i])*(row[j]-means[j]),0)/(obs-1))),sd=cov.map((r,i)=>Math.sqrt(r[i])),corr=cov.map((row,i)=>row.map((v,j)=>sd[i]&&sd[j]?v/(sd[i]*sd[j]):NaN));return{ast:matrixAst(cov),display:`${k}×${k} sample covariance matrix`,exactness:'approximate',warnings:['Columns are interpreted as variables and rows as independent observations. Correlation is undefined for a zero-variance variable.'],sections:[section('covariance','Sample covariance matrix',[{label:'n',display:String(obs)},{label:'Variables',display:String(k)},{label:'Means',display:`[${means.map(v=>fixed(v)).join(', ')}]`,ast:vectorAst(means)},{label:'Covariance',display:cov.map(r=>`[${r.map(v=>fixed(v)).join(', ')}]`).join(' ; '),ast:matrixAst(cov)}]),section('correlation-matrix','Correlation matrix',[{label:'Correlation',display:corr.map(r=>`[${r.map(v=>fixed(v)).join(', ')}]`).join(' ; '),ast:matrixAst(corr)}]) ]};}

function twoColumns(node:AstNode):[Vector,Vector]{const A=numericMatrix(node);if(A[0].length!==2||A.length<2)throw new Error('This E6 two-sample workflow expects an n×2 matrix with one sample per column.');return[A.map(r=>r[0]),A.map(r=>r[1])];}
type Alternative='two-sided'|'less'|'greater';
function tPValue(t:number,df:number,alt:Alternative):number{const c=studentTCdf(t,df);return alt==='less'?c:alt==='greater'?1-c:2*Math.min(c,1-c);}
function zPValue(z:number,alt:Alternative):number{const c=normalCdf(z);return alt==='less'?c:alt==='greater'?1-c:2*Math.min(c,1-c);}
function tCritical(confidence:number,df:number):number{return quantileByCdf((1+confidence)/2,x=>studentTCdf(x,df),0,1);}
export function twoSampleMeanInference(node:AstNode,confidence:number,nullDifference:number,alternative:Alternative):E6Transform{const[a,b]=twoColumns(node),m1=mean(a),m2=mean(b),v1=sampleVariance(a),v2=sampleVariance(b),se=Math.sqrt(v1/a.length+v2/b.length),df=(v1/a.length+v2/b.length)**2/((v1/a.length)**2/(a.length-1)+(v2/b.length)**2/(b.length-1)),diff=m1-m2,t=(diff-nullDifference)/se,critical=tCritical(confidence,df),ci=[diff-critical*se,diff+critical*se],p=tPValue(t,df,alternative);return{ast:vectorAst(ci),display:`Δ≈${fixed(diff)} · p≈${fixed(p)}`,exactness:'approximate',warnings:['Welch two-sample t inference does not assume equal population variances. Independence between the two columns is an analysis assumption that MathLab cannot infer from the numbers alone.'],sections:[section('two-sample','Welch two-sample mean inference',[{label:'n₁ / n₂',display:`${a.length} / ${b.length}`},{label:'Mean₁ / Mean₂',display:`${fixed(m1)} / ${fixed(m2)}`},{label:'Difference',display:fixed(diff)},{label:'SE',display:fixed(se)},{label:'Welch df',display:fixed(df)},{label:'t',display:fixed(t)},{label:'p-value',display:fixed(p,10),tone:p<0.05?'warning':'neutral'},{label:`${fixed(confidence*100,2)}% CI`,display:`[${fixed(ci[0])}, ${fixed(ci[1])}]`,ast:vectorAst(ci)}]) ]};}
export function pairedMeanInference(node:AstNode,confidence:number,nullDifference:number,alternative:Alternative):E6Transform{const[a,b]=twoColumns(node),d=a.map((v,i)=>v-b[i]),m=mean(d),sd=Math.sqrt(sampleVariance(d)),se=sd/Math.sqrt(d.length),df=d.length-1,t=(m-nullDifference)/se,p=tPValue(t,df,alternative),critical=tCritical(confidence,df),ci=[m-critical*se,m+critical*se];return{ast:vectorAst(ci),display:`paired Δ≈${fixed(m)} · p≈${fixed(p)}`,exactness:'approximate',warnings:['Rows are treated as matched pairs; pair ordering is part of the data semantics.'],sections:[section('paired','Paired mean inference',[{label:'Pairs',display:String(d.length)},{label:'Mean difference',display:fixed(m)},{label:'SD differences',display:fixed(sd)},{label:'t',display:fixed(t)},{label:'df',display:String(df)},{label:'p-value',display:fixed(p,10)},{label:`${fixed(confidence*100,2)}% CI`,display:`[${fixed(ci[0])}, ${fixed(ci[1])}]`,ast:vectorAst(ci)}]) ]};}
export function twoProportionInference(node:AstNode,confidence:number,nullDifference:number,alternative:Alternative):E6Transform{const[a,b]=twoColumns(node);for(const value of [...a,...b])if(value!==0&&value!==1)throw new Error('Two-proportion inference expects binary 0/1 observations in both columns.');const x1=a.reduce((s,v)=>s+v,0),x2=b.reduce((s,v)=>s+v,0),p1=x1/a.length,p2=x2/b.length,diff=p1-p2,pooled=(x1+x2)/(a.length+b.length),se0=Math.sqrt(pooled*(1-pooled)*(1/a.length+1/b.length)),z=(diff-nullDifference)/se0,p=zPValue(z,alternative),zcrit=quantileByCdf((1+confidence)/2,normalCdf,0,1),se=Math.sqrt(p1*(1-p1)/a.length+p2*(1-p2)/b.length),ci=[diff-zcrit*se,diff+zcrit*se];return{ast:vectorAst(ci),display:`p₁-p₂≈${fixed(diff)} · p≈${fixed(p)}`,exactness:'approximate',warnings:['The test uses the pooled large-sample z approximation under H₀; the confidence interval uses an unpooled Wald approximation. Small or extreme samples can require exact methods not implemented in E6.'],sections:[section('two-proportion','Two-proportion inference',[{label:'Successes',display:`${x1}/${a.length} vs ${x2}/${b.length}`},{label:'p̂₁ / p̂₂',display:`${fixed(p1)} / ${fixed(p2)}`},{label:'Difference',display:fixed(diff)},{label:'z',display:fixed(z)},{label:'p-value',display:fixed(p,10)},{label:`${fixed(confidence*100,2)}% CI`,display:`[${fixed(ci[0])}, ${fixed(ci[1])}]`,ast:vectorAst(ci)}]) ]};}

export function chiSquareGoodness(node:AstNode,expectedSource:string):E6Transform{const observed=datasetVector(node);if(observed.length<2||observed.some(v=>v<0||!Number.isInteger(v)))throw new Error('Goodness-of-fit observed counts must be nonnegative integers.');const expectedRaw=parseVector(expectedSource,'Expected counts/proportions');if(expectedRaw.length!==observed.length||expectedRaw.some(v=>v<=0))throw new Error('Expected vector must be positive and match the observed category count.');const total=observed.reduce((s,v)=>s+v,0),sumExp=expectedRaw.reduce((s,v)=>s+v,0),expected=Math.abs(sumExp-1)<1e-9?expectedRaw.map(p=>p*total):expectedRaw;if(Math.abs(expected.reduce((s,v)=>s+v,0)-total)>1e-8*Math.max(1,total))throw new Error('Expected counts must sum to the observed total, or expected proportions must sum to 1.');const stat=observed.reduce((s,o,i)=>s+(o-expected[i])**2/expected[i],0),df=observed.length-1,p=1-chiSquareCdf(stat,df);return{ast:n(stat),display:`χ²≈${fixed(stat)} · p≈${fixed(p)}`,exactness:'approximate',warnings:[expected.some(v=>v<5)?'At least one expected count is below 5; the chi-square approximation may be unreliable.':'The chi-square p-value is an asymptotic approximation.'],sections:[section('chi-gof','Chi-square goodness of fit',[{label:'Observed',display:`[${observed.join(', ')}]`},{label:'Expected',display:`[${expected.map(v=>fixed(v)).join(', ')}]`},{label:'χ²',display:fixed(stat)},{label:'df',display:String(df)},{label:'p-value',display:fixed(p,10)}]) ]};}
export function chiSquareIndependence(node:AstNode):E6Transform{const O=numericMatrix(node),r=O.length,c=O[0].length;if(r<2||c<2||O.some(row=>row.some(v=>v<0||!Number.isInteger(v))))throw new Error('Contingency tables require a ≥2×2 matrix of nonnegative integer counts.');const row=O.map(x=>x.reduce((s,v)=>s+v,0)),col=Array.from({length:c},(_,j)=>O.reduce((s,x)=>s+x[j],0)),total=row.reduce((s,v)=>s+v,0);if(total<=0||row.some(v=>v===0)||col.some(v=>v===0))throw new Error('Every contingency-table row and column must have a positive marginal count.');const E=O.map((_,i)=>Array.from({length:c},(_,j)=>row[i]*col[j]/total)),stat=O.reduce((s,x,i)=>s+x.reduce((t,v,j)=>t+(v-E[i][j])**2/E[i][j],0),0),df=(r-1)*(c-1),p=1-chiSquareCdf(stat,df),cramer=Math.sqrt(stat/(total*Math.min(r-1,c-1)));return{ast:n(stat),display:`χ²≈${fixed(stat)} · p≈${fixed(p)} · V≈${fixed(cramer)}`,exactness:'approximate',warnings:[E.flat().some(v=>v<5)?'At least one expected cell count is below 5; consider an exact categorical test.':'The chi-square independence p-value is asymptotic.'],sections:[section('chi-independence','Chi-square test of independence',[{label:'χ²',display:fixed(stat)},{label:'df',display:String(df)},{label:'p-value',display:fixed(p,10)},{label:"Cramér's V",display:fixed(cramer)},{label:'Expected counts',display:E.map(x=>`[${x.map(v=>fixed(v)).join(', ')}]`).join(' ; '),ast:matrixAst(E)}]) ]};}

export function oneWayAnova(node:AstNode):E6Transform{const A=numericMatrix(node),groups=transpose(A),k=groups.length,N=A.length*k;if(k<2||A.length<2)throw new Error('One-way ANOVA expects at least two group columns with at least two observations each.');const means=groups.map(mean),grand=A.flat().reduce((s,v)=>s+v,0)/N,ssb=groups.reduce((s,g,i)=>s+g.length*(means[i]-grand)**2,0),ssw=groups.reduce((s,g,i)=>s+g.reduce((t,v)=>t+(v-means[i])**2,0),0),dfb=k-1,dfw=N-k,msb=ssb/dfb,msw=ssw/dfw,F=msb/msw,p=1-fCdf(F,dfb,dfw),eta=ssb/(ssb+ssw);return{ast:n(F),display:`F≈${fixed(F)} · p≈${fixed(p)}`,exactness:'approximate',warnings:['Columns are treated as independent groups of equal size. ANOVA assumes independent observations and is most reliable with approximately normal errors and comparable group variances.'],sections:[section('anova','One-way ANOVA',[{label:'Groups',display:String(k)},{label:'Total n',display:String(N)},{label:'Group means',display:`[${means.map(v=>fixed(v)).join(', ')}]`},{label:'SS between',display:fixed(ssb)},{label:'SS within',display:fixed(ssw)},{label:'F',display:fixed(F)},{label:'df',display:`${dfb}, ${dfw}`},{label:'p-value',display:fixed(p,10)},{label:'η²',display:fixed(eta)}]) ]};}

interface Ols{beta:Vector;fitted:Vector;residuals:Vector;sse:number;sst:number;r2:number;adjR2:number;df:number;mse:number;xtxInv:Matrix;X:Matrix;y:Vector;}
function ols(A:Matrix):Ols{const rows=A.length,cols=A[0].length;if(cols<2)throw new Error('Regression matrix needs at least one predictor and one response column.');const predictors=cols-1,p=predictors+1;if(rows<=p)throw new Error(`Multiple regression needs more than ${p} observations for ${predictors} predictor(s).`);const X=A.map(row=>[1,...row.slice(0,-1)]),y=A.map(row=>row[cols-1]),Xt=transpose(X),XtX=matmul(Xt,X),xty=matvec(Xt,y),beta=gaussianSolve(XtX,xty),fitted=matvec(X,beta),residuals=y.map((v,i)=>v-fitted[i]),sse=dot(residuals,residuals),ym=mean(y),sst=y.reduce((s,v)=>s+(v-ym)**2,0),r2=sst===0?NaN:1-sse/sst,df=rows-p,mse=sse/df,adjR2=Number.isFinite(r2)?1-(1-r2)*(rows-1)/df:NaN,xtxInv=inverse(XtX);return{beta,fitted,residuals,sse,sst,r2,adjR2,df,mse,xtxInv,X,y};}
export function multipleLinearRegression(node:AstNode):E6Transform{const A=numericMatrix(node),out=ols(A),se=out.beta.map((_,i)=>Math.sqrt(Math.max(0,out.mse*out.xtxInv[i][i]))),t=out.beta.map((b,i)=>b/se[i]),p=t.map(v=>twoSidedFromCdf(v,x=>studentTCdf(x,out.df))),facts:MathResultFact[]=out.beta.map((b,i)=>({label:i===0?'Intercept':`β${i}`,display:`${fixed(b)} · SE=${fixed(se[i])} · t=${fixed(t[i])} · p=${fixed(p[i],8)}`}));return{ast:vectorAst(out.beta),display:`β≈[${out.beta.map(v=>fixed(v)).join(', ')}] · R²≈${fixed(out.r2)}`,exactness:'approximate',warnings:['The final matrix column is the response; preceding columns are predictors. Coefficient p-values use ordinary least-squares t inference and rely on the classical linear-model assumptions.'],sections:[section('multiple-regression','Multiple linear regression',[{label:'Observations',display:String(A.length)},{label:'Predictors',display:String(A[0].length-1)},{label:'Coefficients',display:`[${out.beta.map(v=>fixed(v)).join(', ')}]`,ast:vectorAst(out.beta)},{label:'R²',display:fixed(out.r2)},{label:'Adjusted R²',display:fixed(out.adjR2)},{label:'Residual SE',display:fixed(Math.sqrt(out.mse))},{label:'Residual df',display:String(out.df)}]),section('coefficients','Coefficient inference',facts)]};}
function vifFor(A:Matrix,predictor:number):number{const p=A[0].length-1;if(p<=1)return 1;const reduced=A.map(row=>[...row.slice(0,predictor),...row.slice(predictor+1,p),row[predictor]]);const r=ols(reduced).r2;return Number.isFinite(r)&&r<1?1/(1-r):Infinity;}
export function regressionDiagnostics(node:AstNode):E6Transform{const A=numericMatrix(node),out=ols(A),p=out.beta.length,leverages=out.X.map(row=>dot(row,matvec(out.xtxInv,row))),std=out.residuals.map((r,i)=>r/Math.sqrt(Math.max(1e-30,out.mse*(1-leverages[i])))),cooks=out.residuals.map((r,i)=>(r*r/(p*out.mse))*leverages[i]/Math.max(1e-30,(1-leverages[i])**2)),maxStd=Math.max(...std.map(Math.abs)),maxCook=Math.max(...cooks),vifs=Array.from({length:A[0].length-1},(_,j)=>vifFor(A,j));return{ast:vectorAst(cooks),display:`max |standardized residual|≈${fixed(maxStd)} · max Cook D≈${fixed(maxCook)}`,exactness:'approximate',warnings:['Diagnostics identify numerical warning signals, not automatic proof that regression assumptions hold or fail. Residual plots and subject-matter review remain necessary.'],sections:[section('regression-diagnostics','Regression diagnostics',[{label:'Max |standardized residual|',display:fixed(maxStd),tone:maxStd>3?'warning':'neutral'},{label:"Max Cook's D",display:fixed(maxCook),tone:maxCook>4/A.length?'warning':'neutral'},{label:'Leverage threshold 2p/n',display:fixed(2*p/A.length)},{label:'Max leverage',display:fixed(Math.max(...leverages))},{label:'VIFs',display:`[${vifs.map(v=>fixed(v)).join(', ')}]`,tone:vifs.some(v=>v>10)?'warning':'neutral'}]),section('influence','Per-observation influence',A.map((_,i)=>({label:`Row ${i+1}`,display:`resid=${fixed(out.residuals[i])} · std=${fixed(std[i])} · h=${fixed(leverages[i])} · Cook=${fixed(cooks[i])}`})).slice(0,50),'Output is capped at 50 observations.') ]};}

function ranks(values:Vector):{ranks:Vector;tieSum:number}{const order=values.map((v,i)=>({v,i})).sort((a,b)=>a.v-b.v),out=Array(values.length).fill(0);let tieSum=0;for(let i=0;i<order.length;){let j=i+1;while(j<order.length&&order[j].v===order[i].v)j++;const rank=(i+1+j)/2;for(let k=i;k<j;k++)out[order[k].i]=rank;const t=j-i;if(t>1)tieSum+=t**3-t;i=j;}return{ranks:out,tieSum};}
export function mannWhitney(node:AstNode):E6Transform{const[a,b]=twoColumns(node),all=[...a,...b],ranked=ranks(all),r1=ranked.ranks.slice(0,a.length).reduce((s,v)=>s+v,0),u1=r1-a.length*(a.length+1)/2,u2=a.length*b.length-u1,U=Math.min(u1,u2),N=a.length+b.length,variance=a.length*b.length/12*((N+1)-ranked.tieSum/(N*(N-1))),z=(U-a.length*b.length/2+0.5)/Math.sqrt(variance),p=twoSidedFromCdf(z,normalCdf);return{ast:n(U),display:`U=${fixed(U)} · p≈${fixed(p)}`,exactness:'approximate',warnings:['Mann–Whitney uses a large-sample normal approximation with tie correction and continuity correction. It is not an exact small-sample permutation calculation.'],sections:[section('mann-whitney','Mann–Whitney U test',[{label:'U',display:fixed(U)},{label:'z approximation',display:fixed(z)},{label:'p-value',display:fixed(p,10)}]) ]};}
export function wilcoxonSignedRank(node:AstNode):E6Transform{const[a,b]=twoColumns(node),diff=a.map((v,i)=>v-b[i]).filter(v=>v!==0);if(diff.length<2)throw new Error('Wilcoxon signed-rank requires at least two nonzero paired differences.');const abs=diff.map(Math.abs),ranked=ranks(abs),wplus=diff.reduce((s,v,i)=>s+(v>0?ranked.ranks[i]:0),0),wminus=diff.reduce((s,v,i)=>s+(v<0?ranked.ranks[i]:0),0),W=Math.min(wplus,wminus),nn=diff.length,mu=nn*(nn+1)/4,variance=(nn*(nn+1)*(2*nn+1)-ranked.tieSum/2)/24,z=(W-mu+0.5)/Math.sqrt(variance),p=twoSidedFromCdf(z,normalCdf);return{ast:n(W),display:`W=${fixed(W)} · p≈${fixed(p)}`,exactness:'approximate',warnings:['Zero differences are removed. The p-value is a normal approximation with tie/continuity correction, not an exact signed-rank enumeration.'],sections:[section('wilcoxon','Wilcoxon signed-rank test',[{label:'Nonzero pairs',display:String(nn)},{label:'W+',display:fixed(wplus)},{label:'W−',display:fixed(wminus)},{label:'W',display:fixed(W)},{label:'z approximation',display:fixed(z)},{label:'p-value',display:fixed(p,10)}]) ]};}

export function bootstrapMean(node:AstNode,count:number,confidence:number,seed:number):E6Transform{const x=datasetVector(node);if(x.length<2)throw new Error('Bootstrap mean requires at least two observations.');if(!Number.isInteger(count)||count<100||count>10000)throw new Error('Bootstrap resamples must be an integer from 100 to 10000.');if(!(confidence>0&&confidence<1))throw new Error('Bootstrap confidence must lie between 0 and 1.');const random=rng(seed),means=Array.from({length:count},()=>{let s=0;for(let i=0;i<x.length;i++)s+=x[Math.floor(random()*x.length)];return s/x.length;}).sort((a,b)=>a-b),alpha=(1-confidence)/2,q=(p:number)=>{const pos=p*(means.length-1),lo=Math.floor(pos),hi=Math.ceil(pos),w=pos-lo;return means[lo]*(1-w)+means[hi]*w;},ci=[q(alpha),q(1-alpha)],estimate=mean(x),bias=mean(means)-estimate;return{ast:vectorAst(ci),display:`mean≈${fixed(estimate)} · percentile CI≈[${fixed(ci[0])}, ${fixed(ci[1])}]`,exactness:'heuristic',warnings:['Bootstrap inference is a resampling heuristic conditional on the observed sample; the percentile interval is not an exact coverage guarantee. The seed makes results reproducible.'],sections:[section('bootstrap','Bootstrap mean',[{label:'Observed mean',display:fixed(estimate)},{label:'Resamples',display:String(count)},{label:'Seed',display:String(seed)},{label:'Bootstrap bias',display:fixed(bias)},{label:`${fixed(confidence*100,2)}% percentile CI`,display:`[${fixed(ci[0])}, ${fixed(ci[1])}]`,ast:vectorAst(ci)}]) ]};}

function validateTransition(P:Matrix):void{if(P.length!==P[0].length)throw new Error('A Markov transition matrix must be square.');for(let i=0;i<P.length;i++){if(P[i].some(v=>v<0||v>1))throw new Error('Transition probabilities must lie in [0,1].');const sum=P[i].reduce((s,v)=>s+v,0);if(Math.abs(sum-1)>1e-10)throw new Error(`Transition row ${i+1} must sum to 1; received ${fixed(sum,12)}.`);}}
function communicateAll(P:Matrix):boolean{const n=P.length;for(let start=0;start<n;start++){const seen=new Set([start]),queue=[start];while(queue.length){const u=queue.shift()!;for(let v=0;v<n;v++)if(P[u][v]>1e-14&&!seen.has(v)){seen.add(v);queue.push(v);}}if(seen.size!==n)return false;}return true;}
function stationary(P:Matrix):{pi:Vector;converged:boolean;iterations:number}{let pi=Array(P.length).fill(1/P.length);for(let k=0;k<10000;k++){const next=Array(P.length).fill(0);for(let i=0;i<P.length;i++)for(let j=0;j<P.length;j++)next[j]+=pi[i]*P[i][j];const delta=Math.max(...next.map((v,i)=>Math.abs(v-pi[i])));pi=next;if(delta<1e-13)return{pi,converged:true,iterations:k+1};}return{pi,converged:false,iterations:10000};}
export function markovProfile(node:AstNode):E6Transform{const P=numericMatrix(node);validateTransition(P);const st=stationary(P),irreducible=communicateAll(P),selfLoop=P.some((row,i)=>row[i]>1e-14);return{ast:vectorAst(st.pi),display:`${P.length}-state chain · stationary≈[${st.pi.map(v=>fixed(v)).join(', ')}]`,exactness:'approximate',warnings:[!st.converged?'Power iteration did not converge to the requested numerical threshold.':'Stationary probabilities are computed numerically by power iteration from the uniform distribution.',irreducible&&selfLoop?'The chain is irreducible and has a self-loop, which is sufficient for aperiodicity.':'E6 does not claim a full period decomposition in this foundation phase.'],sections:[section('markov','Finite Markov-chain profile',[{label:'States',display:String(P.length)},{label:'Row stochastic',display:'Yes',tone:'positive'},{label:'Irreducible',display:irreducible?'Yes':'No'},{label:'Has self-loop',display:selfLoop?'Yes':'No'},{label:'Stationary candidate',display:`[${st.pi.map(v=>fixed(v)).join(', ')}]`,ast:vectorAst(st.pi)},{label:'Power iterations',display:String(st.iterations)}]) ]};}
export function markovStep(node:AstNode,initialSource:string,steps:number):E6Transform{const P=numericMatrix(node);validateTransition(P);if(!Number.isInteger(steps)||steps<0||steps>100000)throw new Error('Markov step count must be an integer from 0 to 100000.');let pi=parseVector(initialSource,'Initial distribution');if(pi.length!==P.length||pi.some(v=>v<0)||Math.abs(pi.reduce((s,v)=>s+v,0)-1)>1e-10)throw new Error('Initial distribution must match the state count, be nonnegative, and sum to 1.');for(let k=0;k<steps;k++){const next=Array(P.length).fill(0);for(let i=0;i<P.length;i++)for(let j=0;j<P.length;j++)next[j]+=pi[i]*P[i][j];pi=next;}return{ast:vectorAst(pi),display:`π_${steps}≈[${pi.map(v=>fixed(v)).join(', ')}]`,exactness:'approximate',warnings:['Finite-state propagation is deterministic, but displayed probabilities use binary64 arithmetic.'],sections:[section('markov-step','Markov state propagation',[{label:'Steps',display:String(steps)},{label:'Distribution',display:`[${pi.map(v=>fixed(v)).join(', ')}]`,ast:vectorAst(pi)}]) ]};}
